### ISSUE TITLE
list.sort crashes when list contains string and null

### ISSUE THREAD

**Issue by Andreyul** [JoeStrout/miniscript#47]
Miniscript C# Windows console app sha-1 e0f139

script.mini:
```
list = []
list.push("test")
list.push(null)
list.sort

```

Console output:
```
f:\Miniscript>Miniscript.exe script.mini

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Miniscript.Value.Compare(Value x, Value y)
   at Miniscript.ValueSorter.Compare(Value x, Value y)
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Miniscript.Intrinsics.<>c.<InitIfNeeded>b__2_38(Context context, Result partialResult)
   at Miniscript.Intrinsic.Execute(Int32 id, Context context, Result partialResult)
   at Miniscript.TAC.Line.Evaluate(Context context)
   at Miniscript.TAC.Machine.DoOneLine(Line line, Context context)
   at Miniscript.TAC.Machine.Step()
   at Miniscript.Interpreter.RunUntilDone(Double timeLimit, Boolean returnEarly)
   at MainClass.RunFile(String path, Boolean dumpTAC)
   at MainClass.Main(String[] args)

f:\Miniscript>
```

**Comment by JoeStrout** [comment]
Confirmed.  Thanks for the report, I expect to push a fix this weekend!
